# pytest.ini
[pytest]
pythonpath = .
filterwarnings =
    ignore::DeprecationWarning:importlib._bootstrap
    ignore:builtin type SwigPyPacked has no.*:DeprecationWarning
    ignore:builtin type SwigPyObject has no.*:DeprecationWarning
    ignore:builtin type swigvarlink has no.*:DeprecationWarning